apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: { name: kv-seclab, namespace: app }
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "7bd21f13-505f-46e8-b093-b8f0787953a9"   # clientId id-seclab-dev
    keyvaultName: kv-seclab-main
    tenantId: "413600cf-bd4e-4c7c-8a61-69e73cddf731"
    objects: |
      array:
        - |
          objectName: secret-test
          objectType: secret
